version: 2

defaults: &defaults
  docker:
  - image: robcasey/dev:echidna

workflows:
  version: 2
  build-pipeline:
    jobs:
      - test

jobs:

  test:
    <<: *defaults
    steps:
      - checkout
      - run: make tests
      - codecov/upload:
          file: gcovr.xml
          token: d84db9b8-dbbe-4fb8-8d60-a93985c1e766
      
  build:
    <<: *defaults
    steps:
      - run: make

