version: 2

defaults: &defaults
  docker:
  - image: robcasey/dev:echidna

workflows:
  version: 2
  nightly-pipeline:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test

jobs:

  test:
    <<: *defaults
    steps:
      - checkout
      - run: make tests
      - store_artifacts:
          path: gcovr.txt
      
  build:
    <<: *defaults
    steps:
      - run: make

