#ifndef _RUNTIME_ERROR_H
#define _RUNTIME_ERROR_H


typedef enum _RUNTIME_ERROR {

    RT_ERR_NONE = 0,
    RT_ERR_INTERNAL,
    RT_ERR_INTERNAL_ALLOCATION,
    RT_ERR_INTERNAL_READ,
    RT_ERR_INTERNAL_WRITE,
    RT_ERR_INVALID_BYTECODE,
    RT_ERR_INVALID_SYMBOL,
    RT_ERR_INVALID_FUNCTION,
    RT_ERR_INVALID_LENGTH,
    RT_ERR_DIVIDE_ZERO,
    RT_ERR_MODULUS_ZERO,
    RT_ERR_MATH_OVERFLOW,
    RT_ERR_OPERAND_TYPE,
    RT_ERR_PARAMETER_COUNT,
    RT_ERR_PARAMETER_MISMATCH,
    RT_ERR_PARAMETER_RANGE,
    RT_ERR_PARAMETER_TYPE,
    RT_ERR_PARAMETER_UNKNOWN,
    RT_ERR_STACK_OVERFLOW,
    RT_ERR_UNIMPLEMENTED,
}
RUNTIME_ERROR;


const char * runtime_errortostr(int Error);


#endif  //  _RUNTIME_ERROR_H
