#include <stdint.h>

#include <echidna.h>
#include <function.h>
#include <standard.h>
#include <standard/arithmetic.h>
#include <standard/bitstring.h>
#include <standard/bitwise.h>
#include <standard/fb.h>
#include <standard/numeric.h>
#include <standard/select.h>
#include <standard/string.h>
#include <standard/type.h>


int
standard_initialise(ECHIDNA *Context) {
    int nResult;

    if(((nResult = echidna_register(Context, "abs", TYPE_FUNCTION, standard_abs)) != 0) ||
            ((nResult = echidna_register(Context, "acos", TYPE_FUNCTION, standard_acos)) != 0) ||
            ((nResult = echidna_register(Context, "add", TYPE_FUNCTION, standard_add)) != 0) ||
            ((nResult = echidna_register(Context, "add_date_time", TYPE_FUNCTION, standard_add)) != 0) ||
            ((nResult = echidna_register(Context, "add_dt_time", TYPE_FUNCTION, standard_add)) != 0) ||
            ((nResult = echidna_register(Context, "add_time", TYPE_FUNCTION, standard_add)) != 0) ||
            ((nResult = echidna_register(Context, "add_tod_time", TYPE_FUNCTION, standard_add)) != 0) ||
            ((nResult = echidna_register(Context, "and", TYPE_FUNCTION, standard_and)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "any_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "asin", TYPE_FUNCTION, standard_asin)) != 0) ||
            ((nResult = echidna_register(Context, "atan", TYPE_FUNCTION, standard_atan)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "bool_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_bcd_to_usint", TYPE_FUNCTION, standard_bcd)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "byte_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "concat", TYPE_FUNCTION, standard_concat)) != 0) ||
            ((nResult = echidna_register(Context, "cos", TYPE_FUNCTION, standard_cos)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_and_time_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "date_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "delete", TYPE_FUNCTION, standard_delete)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dint_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "div", TYPE_FUNCTION, standard_div)) != 0) ||
            ((nResult = echidna_register(Context, "divtime", TYPE_FUNCTION, standard_div)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dt_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_bcd_to_udint", TYPE_FUNCTION, standard_bcd)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "dword_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "eq", TYPE_FUNCTION, standard_eq)) != 0) ||
            ((nResult = echidna_register(Context, "exp", TYPE_FUNCTION, standard_exp)) != 0) ||
            ((nResult = echidna_register(Context, "expt", TYPE_FUNCTION, standard_expt)) != 0) ||
            ((nResult = echidna_register(Context, "find", TYPE_FUNCTION, standard_find)) != 0) ||
            ((nResult = echidna_register(Context, "insert", TYPE_FUNCTION, standard_insert)) != 0) ||
            ((nResult = echidna_register(Context, "ge", TYPE_FUNCTION, standard_ge)) != 0) ||
            ((nResult = echidna_register(Context, "gt", TYPE_FUNCTION, standard_gt)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "int_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "le", TYPE_FUNCTION, standard_le)) != 0) ||
            ((nResult = echidna_register(Context, "len", TYPE_FUNCTION, standard_len)) != 0) ||
            ((nResult = echidna_register(Context, "left", TYPE_FUNCTION, standard_left)) != 0) ||
            ((nResult = echidna_register(Context, "limit", TYPE_FUNCTION, standard_limit)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lint_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ln", TYPE_FUNCTION, standard_ln)) != 0) ||
            ((nResult = echidna_register(Context, "log", TYPE_FUNCTION, standard_log)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lreal_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lt", TYPE_FUNCTION, standard_lt)) != 0) ||
            ((nResult = echidna_register(Context, "lword_bcd_to_ulint", TYPE_FUNCTION, standard_bcd)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "lword_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "max", TYPE_FUNCTION, standard_max)) != 0) ||
            ((nResult = echidna_register(Context, "mid", TYPE_FUNCTION, standard_mid)) != 0) ||
            ((nResult = echidna_register(Context, "min", TYPE_FUNCTION, standard_min)) != 0) ||
            ((nResult = echidna_register(Context, "mod", TYPE_FUNCTION, standard_mod)) != 0) ||
            ((nResult = echidna_register(Context, "mul", TYPE_FUNCTION, standard_mul)) != 0) ||
            ((nResult = echidna_register(Context, "multime", TYPE_FUNCTION, standard_mul)) != 0) ||
            ((nResult = echidna_register(Context, "mux", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_lreal", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_real", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_lint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_dint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_int", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_sint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_ulint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_udint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_uint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_usint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_lword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_dword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_word", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_byte", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_dint_bool", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_lreal", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_real", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_lint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_dint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_int", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_sint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_ulint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_udint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_uint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_usint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_lword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_dword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_word", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_byte", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_int_bool", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_lreal", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_real", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_lint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_dint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_int", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_sint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_ulint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_udint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_uint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_usint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_lword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_dword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_word", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_byte", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_lint_bool", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_lreal", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_real", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_lint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_dint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_int", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_sint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_ulint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_udint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_uint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_usint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_lword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_dword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_word", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_byte", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_sint_bool", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_lreal", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_real", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_lint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_dint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_int", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_sint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_ulint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_udint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_uint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_usint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_lword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_dword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_word", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_byte", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_udint_bool", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_lreal", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_real", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_lint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_dint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_int", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_sint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_ulint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_udint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_uint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_usint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_lword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_dword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_word", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_byte", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_uint_bool", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_lreal", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_real", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_lint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_dint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_int", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_sint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_ulint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_udint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_uint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_usint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_lword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_dword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_word", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_byte", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_ulint_bool", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_lreal", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_real", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_lint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_dint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_int", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_sint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_ulint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_udint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_uint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_usint", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_lword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_dword", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_word", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_byte", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "mux_usint_bool", TYPE_FUNCTION, standard_mux)) != 0) ||
            ((nResult = echidna_register(Context, "ne", TYPE_FUNCTION, standard_ne)) != 0) ||
            ((nResult = echidna_register(Context, "or", TYPE_FUNCTION, standard_or)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "real_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "replace", TYPE_FUNCTION, standard_replace)) != 0) ||
            ((nResult = echidna_register(Context, "right", TYPE_FUNCTION, standard_right)) != 0) ||
            ((nResult = echidna_register(Context, "rol", TYPE_FUNCTION, standard_rol)) != 0) ||
            ((nResult = echidna_register(Context, "ror", TYPE_FUNCTION, standard_ror)) != 0) ||
            ((nResult = echidna_register(Context, "sel", TYPE_FUNCTION, standard_sel)) != 0) ||
            ((nResult = echidna_register(Context, "shl", TYPE_FUNCTION, standard_shl)) != 0) ||
            ((nResult = echidna_register(Context, "shr", TYPE_FUNCTION, standard_shr)) != 0) ||
            ((nResult = echidna_register(Context, "sin", TYPE_FUNCTION, standard_sin)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sint_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sqrt", TYPE_FUNCTION, standard_shr)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "string_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "sub", TYPE_FUNCTION, standard_sub)) != 0) ||
            ((nResult = echidna_register(Context, "sub_date_date", TYPE_FUNCTION, standard_sub)) != 0) ||
            ((nResult = echidna_register(Context, "sub_date_time", TYPE_FUNCTION, standard_sub)) != 0) ||
            ((nResult = echidna_register(Context, "sub_dt_dt", TYPE_FUNCTION, standard_sub)) != 0) ||
            ((nResult = echidna_register(Context, "sub_dt_time", TYPE_FUNCTION, standard_sub)) != 0) ||
            ((nResult = echidna_register(Context, "sub_time", TYPE_FUNCTION, standard_sub)) != 0) ||
            ((nResult = echidna_register(Context, "sub_tod_time", TYPE_FUNCTION, standard_sub)) != 0) ||
            ((nResult = echidna_register(Context, "tan", TYPE_FUNCTION, standard_tan)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_of_day_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "time_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "tod_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "trunc", TYPE_FUNCTION, standard_trunc)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_bcd_dword", TYPE_FUNCTION, standard_bcd)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "udint_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_bcd_word", TYPE_FUNCTION, standard_bcd)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "uint_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_bcd_lword", TYPE_FUNCTION, standard_bcd)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "ulint_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_bcd_byte", TYPE_FUNCTION, standard_bcd)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "usint_to_word", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_bcd_to_uint", TYPE_FUNCTION, standard_bcd)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_bool", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_byte", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_date", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_date_and_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_dint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_dt", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_dword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_int", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_lint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_lreal", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_lword", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_real", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_sint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_string", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_time", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_time_of_day", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_tod", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_udint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_uint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_ulint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "word_to_usint", TYPE_FUNCTION, standard_type)) != 0) ||
            ((nResult = echidna_register(Context, "xor", TYPE_FUNCTION, standard_xor)) != 0))
        return nResult;

    if(((nResult = standard_bistable(Context)) != 0) ||
            ((nResult = standard_counters(Context)) != 0) ||
            ((nResult = standard_edge(Context)) != 0) ||
            ((nResult = standard_rtc(Context)) != 0) ||
            ((nResult = standard_timers(Context)) != 0))
        return nResult;

    return 0;
}

